/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sy_rootingchecker_test_Ctest */

#ifndef _Included_com_sy_rootingchecker_test_Ctest
#define _Included_com_sy_rootingchecker_test_Ctest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sy_rootingchecker_test_Ctest
 * Method:    enableTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sy_rootingchecker_test_Ctest_enableTest
  (JNIEnv *, jobject);

/*
 * Class:     com_sy_rootingchecker_test_Ctest
 * Method:    disableTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sy_rootingchecker_test_Ctest_disableTest
  (JNIEnv *, jobject);

/*
 * Class:     com_sy_rootingchecker_test_Ctest
 * Method:    setExeclReturnValue
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sy_rootingchecker_test_Ctest_setExeclReturnValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sy_rootingchecker_test_Ctest
 * Method:    setPopenCommandValue
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sy_rootingchecker_test_Ctest_setPopenCommandValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sy_rootingchecker_test_Ctest
 * Method:    setAccessReturnValue
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sy_rootingchecker_test_Ctest_setAccessReturnValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sy_rootingchecker_test_Ctest
 * Method:    setSystemPropertyValue
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sy_rootingchecker_test_Ctest_setSystemPropertyValue
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
