/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sy_rootingchecker_test_ctest */

#ifndef _Included_com_sy_rootingchecker_test_ctest
#define _Included_com_sy_rootingchecker_test_ctest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sy_rootingchecker_test_ctest
 * Method:    enableTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sy_rootingchecker_test_ctest_enableTest
  (JNIEnv *, jobject);

/*
 * Class:     com_sy_rootingchecker_test_ctest
 * Method:    disableTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sy_rootingchecker_test_ctest_disableTest
  (JNIEnv *, jobject);

/*
 * Class:     com_sy_rootingchecker_test_ctest
 * Method:    setExeclReturnValue
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sy_rootingchecker_test_ctest_setExeclReturnValue
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
